import { existsSync, lstatSync, symlinkSync, unlinkSync, rmSync } from "fs";
import path from "path";

type Run = { ok: boolean; out: string; err: string };

async function git(args: string[], cwd: string): Promise<Run> {
  const proc = Bun.spawn(["git", ...args], { cwd, stdout: "pipe", stderr: "pipe" });
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { ok: code === 0, out: out.trim(), err: err.trim() };
}

async function sh(cmd: string[], cwd: string): Promise<Run> {
  const proc = Bun.spawn(cmd, { cwd, stdout: "pipe", stderr: "pipe" });
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { ok: code === 0, out: out.trim(), err: err.trim() };
}

async function commitFiles(repoPath: string, sha: string): Promise<string[]> {
  const r = await git(["diff-tree", "--no-commit-id", "-r", "--name-only", sha], repoPath);
  return r.ok && r.out ? r.out.split("\n").filter(Boolean) : [];
}

export type I18nCheck = {
  hasPo: boolean;
  hasI18nCode: boolean;
  mismatch: boolean;
};

export async function checkI18n(repoPath: string, sha: string): Promise<I18nCheck> {
  const [files, showR] = await Promise.all([
    commitFiles(repoPath, sha),
    git(["show", "--format=", "-U0", sha], repoPath),
  ]);
  const hasPo = files.some((f) => f.endsWith(".po") || f.endsWith(".pot"));
  const hasI18nCode =
    showR.ok &&
    showR.out
      .split("\n")
      .filter((l) => l.startsWith("+") && !l.startsWith("+++"))
      .some((l) => /\bi18n\b|useT\b|t\(['"`]/.test(l));
  return { hasPo, hasI18nCode, mismatch: hasPo !== hasI18nCode };
}

/** Skip auto-fix commits generated by chong itself to avoid re-checking them. */
export async function isAutoFix(repoPath: string, sha: string): Promise<boolean> {
  const r = await git(["log", "-1", "--format=%s", sha], repoPath);
  return r.ok && r.out.startsWith("FIX:");
}

export type ShadowInfo = { shadowPath: string; error: string | null };

/** Ensure the main-shadow worktree exists and is hard-reset to `ref`. */
export async function ensureShadow(repoPath: string, ref: string): Promise<ShadowInfo> {
  const shadowPath = path.join(path.dirname(repoPath), "main-shadow");

  // Prune stale worktree entries first
  await git(["worktree", "prune"], repoPath);

  const listR = await git(["worktree", "list", "--porcelain"], repoPath);
  const linked = listR.out
    .split("\n")
    .some((l) => l.startsWith("worktree ") && l.slice("worktree ".length).trim() === shadowPath);

  if (!linked) {
    const addR = await git(["worktree", "add", "--detach", shadowPath, ref], repoPath);
    if (!addR.ok) return { shadowPath, error: `worktree add: ${addR.err}` };
  } else {
    // Remove stale index.lock before touching the worktree
    const gitDirR = await git(["rev-parse", "--git-dir"], shadowPath);
    if (gitDirR.ok) {
      const lock = path.join(gitDirR.out, "index.lock");
      try { unlinkSync(lock); } catch { /* doesn't exist, fine */ }
    }

    await git(["clean", "-fd"], shadowPath);
    const resetR = await git(["reset", "--hard", ref], shadowPath);
    if (!resetR.ok) return { shadowPath, error: `reset to ${ref}: ${resetR.err}` };
  }

  // Symlink node_modules from the source repo — same lockfile, avoids pnpm hoisting
  // differences and is much faster than a fresh install.
  const nmSource = path.join(repoPath, "node_modules");
  const nmLink = path.join(shadowPath, "node_modules");
  if (existsSync(nmLink)) {
    const stat = lstatSync(nmLink);
    if (!stat.isSymbolicLink()) rmSync(nmLink, { recursive: true, force: true });
    else unlinkSync(nmLink);
  }
  symlinkSync(nmSource, nmLink);

  return { shadowPath, error: null };
}

export type FixResult = {
  committed: boolean;
  pushed: boolean;
  leftovers: string[];
  error: string | null;
};

/** Run `pnpm i18n` in shadow, commit .po/.pot changes, push. Returns leftover files. */
export async function runI18nFix(
  repoPath: string,
  shadowPath: string,
  remote: string,
  branch: string,
): Promise<FixResult> {
  const r = await sh(["pnpm", "i18n"], shadowPath);
  if (!r.ok) {
    return { committed: false, pushed: false, leftovers: [], error: `pnpm i18n: ${r.err || r.out}` };
  }

  const statusR = await git(["status", "--porcelain"], shadowPath);
  if (!statusR.out) return { committed: false, pushed: false, leftovers: [], error: null };

  const changed = statusR.out
    .split("\n")
    .filter(Boolean)
    .map((l) => l.slice(3).trim());
  const poFiles = changed.filter((f) => f.endsWith(".po") || f.endsWith(".pot"));
  const leftovers = changed.filter((f) => !f.endsWith(".po") && !f.endsWith(".pot"));

  if (poFiles.length === 0) return { committed: false, pushed: false, leftovers, error: null };

  await git(["add", "--", ...poFiles], shadowPath);
  const commitR = await git(["commit", "-m", "FIX: pnpm i18n", "--no-verify"], shadowPath);
  if (!commitR.ok) {
    return { committed: false, pushed: false, leftovers, error: `commit: ${commitR.err}` };
  }

  const pushR = await git(["push", remote, `HEAD:refs/heads/${branch}`], shadowPath);
  if (!pushR.ok) {
    return { committed: true, pushed: false, leftovers, error: `push: ${pushR.err}` };
  }

  return { committed: true, pushed: true, leftovers, error: null };
}

/**
 * Run the formatter in shadow, commit formatting changes only for files touched by `sha`,
 * revert all other formatter changes, push.
 */
export async function runFormatFix(
  repoPath: string,
  shadowPath: string,
  sha: string,
  formatCmd: string,
  remote: string,
  branch: string,
): Promise<FixResult> {
  const files = await commitFiles(repoPath, sha);
  if (files.length === 0) return { committed: false, pushed: false, leftovers: [], error: null };

  const [cmd, ...cmdArgs] = formatCmd.trim().split(/\s+/);
  await sh([cmd, ...cmdArgs], shadowPath);
  // Ignore exit code — formatters exit 1 when they modify files

  const statusR = await git(["status", "--porcelain"], shadowPath);
  if (!statusR.out) return { committed: false, pushed: false, leftovers: [], error: null };

  const modified = statusR.out
    .split("\n")
    .filter(Boolean)
    .map((l) => l.slice(3).trim());

  const toCommit = files.filter((f) => modified.includes(f));
  const toRevert = modified.filter((f) => !files.includes(f));

  // Revert formatting changes on files not part of this commit
  if (toRevert.length > 0) {
    await git(["checkout", "--", ...toRevert], shadowPath);
    await git(["clean", "-fd"], shadowPath);
  }

  if (toCommit.length === 0) return { committed: false, pushed: false, leftovers: [], error: null };

  await git(["add", "--", ...toCommit], shadowPath);
  const commitR = await git(["commit", "-m", "FIX: code formatting", "--no-verify"], shadowPath);
  if (!commitR.ok) {
    return { committed: false, pushed: false, leftovers: [], error: `commit: ${commitR.err}` };
  }

  const pushR = await git(["push", remote, `HEAD:refs/heads/${branch}`], shadowPath);
  if (!pushR.ok) {
    return { committed: true, pushed: false, leftovers: [], error: `push: ${pushR.err}` };
  }

  return { committed: true, pushed: true, leftovers: [], error: null };
}
