import { createHash } from "node:crypto";
import { lstatSync, mkdirSync, rmSync, symlinkSync, unlinkSync } from "fs";
import { homedir } from "node:os";
import path from "path";

type Run = { ok: boolean; out: string; err: string };

async function git(args: string[], cwd: string): Promise<Run> {
  const proc = Bun.spawn(["git", ...args], { cwd, stdout: "pipe", stderr: "pipe" });
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { ok: code === 0, out: out.trim(), err: err.trim() };
}

async function sh(cmd: string[], cwd: string): Promise<Run> {
  const proc = Bun.spawn(cmd, { cwd, stdout: "pipe", stderr: "pipe" });
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { ok: code === 0, out: out.trim(), err: err.trim() };
}

async function commitFiles(repoPath: string, sha: string): Promise<string[]> {
  const r = await git(["diff-tree", "--no-commit-id", "-r", "--name-only", sha], repoPath);
  return r.ok && r.out ? r.out.split("\n").filter(Boolean) : [];
}

export type I18nCheck = {
  hasPo: boolean;
  hasI18nCode: boolean;
  mismatch: boolean;
};

export async function checkI18n(repoPath: string, sha: string): Promise<I18nCheck> {
  const [files, showR] = await Promise.all([
    commitFiles(repoPath, sha),
    git(["show", "--format=", "-U0", sha], repoPath),
  ]);
  const hasPo = files.some((f) => f.endsWith(".po") || f.endsWith(".pot"));
  const hasI18nCode =
    showR.ok &&
    showR.out
      .split("\n")
      .filter((l) => l.startsWith("+") && !l.startsWith("+++"))
      .some((l) => /\bi18n\b|useT\b|t\(['"`]/.test(l));
  return { hasPo, hasI18nCode, mismatch: hasPo !== hasI18nCode };
}

/** Skip auto-fix commits generated by chong itself to avoid re-checking them. */
export async function isAutoFix(repoPath: string, sha: string): Promise<boolean> {
  const r = await git(["log", "-1", "--format=%s", sha], repoPath);
  return r.ok && (r.out.startsWith("FIX:") || r.out.startsWith("CLEAN:"));
}

export type ShadowInfo = { shadowPath: string; error: string | null };

/**
 * Where chong keeps a repo's main-shadow worktree: under ~/.chong/worktrees/ rather
 * than as a sibling of the repo, so unrelated tooling (and the user) never trip over
 * it. Keyed by repo basename + a short hash of the absolute top-level path, so two
 * checkouts that share a basename get distinct shadow worktrees.
 */
export function shadowPathFor(repoPath: string): string {
  const base = path.basename(repoPath);
  const hash = createHash("sha1").update(repoPath).digest("hex").slice(0, 8);
  return path.join(homedir(), ".chong", "worktrees", `${base}-main-shadow-${hash}`);
}

/** Ensure the main-shadow worktree exists and is hard-reset to `ref`. */
export async function ensureShadow(repoPath: string, ref: string): Promise<ShadowInfo> {
  const shadowPath = shadowPathFor(repoPath);
  mkdirSync(path.dirname(shadowPath), { recursive: true });

  // Prune stale worktree entries first
  await git(["worktree", "prune"], repoPath);

  // Migrate away from the old sibling location (../main-shadow), if one is still
  // registered, so we don't leave an orphaned worktree behind.
  const legacyPath = path.join(path.dirname(repoPath), "main-shadow");
  if (legacyPath !== shadowPath) {
    const reg = await git(["worktree", "list", "--porcelain"], repoPath);
    const legacyLinked = reg.out
      .split("\n")
      .some((l) => l.startsWith("worktree ") && l.slice("worktree ".length).trim() === legacyPath);
    if (legacyLinked) await git(["worktree", "remove", "--force", legacyPath], repoPath);
  }

  const listR = await git(["worktree", "list", "--porcelain"], repoPath);
  const linked = listR.out
    .split("\n")
    .some((l) => l.startsWith("worktree ") && l.slice("worktree ".length).trim() === shadowPath);

  if (!linked) {
    const addR = await git(["worktree", "add", "--detach", shadowPath, ref], repoPath);
    if (!addR.ok) return { shadowPath, error: `worktree add: ${addR.err}` };
  } else {
    // Remove stale index.lock before touching the worktree
    const gitDirR = await git(["rev-parse", "--git-dir"], shadowPath);
    if (gitDirR.ok) {
      const lock = path.join(gitDirR.out, "index.lock");
      try {
        unlinkSync(lock);
      } catch {
        /* doesn't exist, fine */
      }
    }

    await git(["clean", "-fd"], shadowPath);
    const resetR = await git(["reset", "--hard", ref], shadowPath);
    if (!resetR.ok) return { shadowPath, error: `reset to ${ref}: ${resetR.err}` };
  }

  // Symlink node_modules from the source repo — same lockfile, avoids pnpm hoisting
  // differences and is much faster than a fresh install. Clear any existing entry
  // (real dir or stale/dangling symlink) with lstat so we don't follow the link.
  const nmSource = path.join(repoPath, "node_modules");
  const nmLink = path.join(shadowPath, "node_modules");
  try {
    const stat = lstatSync(nmLink);
    if (stat.isSymbolicLink()) unlinkSync(nmLink);
    else rmSync(nmLink, { recursive: true, force: true });
  } catch {
    /* nothing there yet */
  }
  symlinkSync(nmSource, nmLink);

  return { shadowPath, error: null };
}

export type FixResult = {
  committed: boolean;
  pushed: boolean;
  leftovers: string[];
  error: string | null;
};

/** Run `pnpm i18n` in shadow, commit .po/.pot changes, push. Returns leftover files. */
export async function runI18nFix(
  repoPath: string,
  shadowPath: string,
  remote: string,
  branch: string,
): Promise<FixResult> {
  const r = await sh(["pnpm", "i18n"], shadowPath);
  if (!r.ok) {
    return {
      committed: false,
      pushed: false,
      leftovers: [],
      error: `pnpm i18n: ${r.err || r.out}`,
    };
  }

  const statusR = await git(["status", "--porcelain"], shadowPath);
  if (!statusR.out) return { committed: false, pushed: false, leftovers: [], error: null };

  const changed = statusR.out
    .split("\n")
    .filter(Boolean)
    .map((l) => l.slice(3).trim());
  const poFiles = changed.filter((f) => f.endsWith(".po") || f.endsWith(".pot"));
  const leftovers = changed.filter((f) => !f.endsWith(".po") && !f.endsWith(".pot"));

  if (poFiles.length === 0) return { committed: false, pushed: false, leftovers, error: null };

  await git(["add", "--", ...poFiles], shadowPath);
  const commitR = await git(["commit", "-m", "FIX: pnpm i18n", "--no-verify"], shadowPath);
  if (!commitR.ok) {
    return { committed: false, pushed: false, leftovers, error: `commit: ${commitR.err}` };
  }

  const pushR = await git(["push", remote, `HEAD:refs/heads/${branch}`], shadowPath);
  if (!pushR.ok) {
    return { committed: true, pushed: false, leftovers, error: `push: ${pushR.err}` };
  }

  return { committed: true, pushed: true, leftovers, error: null };
}

/**
 * Run the formatter in shadow, commit formatting changes only for files touched by `sha`,
 * revert all other formatter changes, push.
 */
export async function runFormatFix(
  repoPath: string,
  shadowPath: string,
  sha: string,
  formatCmd: string,
  remote: string,
  branch: string,
): Promise<FixResult> {
  const files = await commitFiles(repoPath, sha);
  if (files.length === 0) return { committed: false, pushed: false, leftovers: [], error: null };

  const [cmd, ...cmdArgs] = formatCmd.trim().split(/\s+/);
  await sh([cmd, ...cmdArgs], shadowPath);
  // Ignore exit code — formatters exit 1 when they modify files

  const statusR = await git(["status", "--porcelain"], shadowPath);
  if (!statusR.out) return { committed: false, pushed: false, leftovers: [], error: null };

  const modified = statusR.out
    .split("\n")
    .filter(Boolean)
    .map((l) => l.slice(3).trim());

  const toCommit = files.filter((f) => modified.includes(f));
  const toRevert = modified.filter((f) => !files.includes(f));

  // Revert formatting changes on files not part of this commit
  if (toRevert.length > 0) {
    await git(["checkout", "--", ...toRevert], shadowPath);
    await git(["clean", "-fd"], shadowPath);
  }

  if (toCommit.length === 0) return { committed: false, pushed: false, leftovers: [], error: null };

  await git(["add", "--", ...toCommit], shadowPath);
  const commitR = await git(["commit", "-m", "FIX: code formatting", "--no-verify"], shadowPath);
  if (!commitR.ok) {
    return { committed: false, pushed: false, leftovers: [], error: `commit: ${commitR.err}` };
  }

  const pushR = await git(["push", remote, `HEAD:refs/heads/${branch}`], shadowPath);
  if (!pushR.ok) {
    return { committed: true, pushed: false, leftovers: [], error: `push: ${pushR.err}` };
  }

  return { committed: true, pushed: true, leftovers: [], error: null };
}

// ── maintenance (manual, [m] in the TUI) ─────────────────────────────────────

/** A ready-to-paste prompt for an LLM to fix something maintenance couldn't. */
export type MaintPrompt = { title: string; text: string };

export type MaintResult = {
  steps: string[]; // human-readable log of what each step did, in order
  prompts: MaintPrompt[]; // copy-friendly LLM prompts for whatever isn't perfect
  error: string | null; // a fatal error that aborted the run
};

// Built via RegExp so the ESC control char isn't a literal in a regex (biome rule).
const ANSI_RE = new RegExp(`${String.fromCharCode(27)}\\[[0-9;]*m`, "g");
const stripAnsi = (s: string) => s.replace(ANSI_RE, "");
const major = (v: string) => Number.parseInt(v.replace(/^[^\d]*/, "").split(".")[0] ?? "", 10);

/** Last `n` non-empty lines of `s`, ANSI-stripped — a compact failure excerpt. */
function tail(s: string, n: number): string {
  const lines = stripAnsi(s)
    .split("\n")
    .map((l) => l.trimEnd())
    .filter(Boolean);
  return lines.slice(-n).join("\n");
}

/** Unique test-file paths mentioned in runner output (`*.test.ts`, `*.spec.tsx`, …). */
function failingTestFiles(output: string): string[] {
  const re = /[\w./@-]*[\w-]+\.(?:test|spec)\.[cm]?[jt]sx?/g;
  return [...new Set(stripAnsi(output).match(re) ?? [])];
}

/**
 * Manual maintenance pass, run in the main-shadow worktree:
 *   1. apply minor (same-major) `pnpm outdated` updates, commit + push
 *   2. run the formatter, commit `CLEAN: code style` + push
 *   3. `pnpm test` — on failure, emit a copy-friendly LLM prompt scoped to the broken test
 *   4. `pnpm i18n` — if it leaves the tree dirty or errors, emit a copy-friendly LLM prompt
 * Steps 1–2 commit with a `CLEAN:` prefix so isAutoFix skips re-checking them.
 */
export async function runMaintenance(
  repoPath: string,
  shadowPath: string,
  cmds: { format: string; test: string; i18n: string },
  remote: string,
  branch: string,
  onStep?: (msg: string) => void,
): Promise<MaintResult> {
  const steps: string[] = [];
  const prompts: MaintPrompt[] = [];
  const step = (msg: string) => {
    steps.push(msg);
    onStep?.(msg);
  };
  const push = async () => git(["push", remote, `HEAD:refs/heads/${branch}`], shadowPath);

  // ── 1. minor dependency updates
  onStep?.("deps: checking pnpm outdated…");
  const outdated = await sh(["pnpm", "outdated", "--format", "json"], shadowPath);
  let targets: string[] = [];
  try {
    const data = JSON.parse(outdated.out || "{}") as Record<
      string,
      { current?: string; latest?: string; wanted?: string }
    >;
    for (const [name, info] of Object.entries(data)) {
      const current = info.current ?? "";
      const latest = info.latest ?? info.wanted ?? "";
      if (!current || !latest || current === latest) continue;
      if (major(current) === major(latest)) targets.push(`${name}@${latest}`);
    }
  } catch {
    targets = [];
  }
  if (targets.length === 0) {
    step("✓ deps: no minor updates available");
  } else {
    // --lockfile-only keeps node_modules (symlinked from the source repo) untouched.
    const up = await sh(["pnpm", "update", "--lockfile-only", ...targets], shadowPath);
    const dirty = (await git(["status", "--porcelain"], shadowPath)).out;
    if (up.ok && dirty) {
      await git(["add", "-A"], shadowPath);
      await git(["commit", "-m", "CLEAN: bump minor deps", "--no-verify"], shadowPath);
      const pr = await push();
      step(
        pr.ok
          ? `✓ deps: updated ${targets.length} package(s) → committed & pushed to ${branch}`
          : `⚠ deps: committed but push failed (${pr.err})`,
      );
    } else if (!up.ok) {
      step(`⚠ deps: pnpm update failed (${up.err || up.out})`);
    } else {
      step("✓ deps: nothing changed");
    }
  }

  // ── 2. code formatting
  onStep?.("format: running formatter…");
  const [fcmd, ...fargs] = cmds.format.trim().split(/\s+/);
  await sh([fcmd, ...fargs], shadowPath); // formatters exit non-zero when they rewrite files
  const fmtDirty = (await git(["status", "--porcelain"], shadowPath)).out;
  if (fmtDirty) {
    await git(["add", "-A"], shadowPath);
    await git(["commit", "-m", "CLEAN: code style", "--no-verify"], shadowPath);
    const pr = await push();
    step(
      pr.ok
        ? `✓ code style: committed & pushed to ${branch}`
        : `⚠ code style: committed but push failed (${pr.err})`,
    );
  } else {
    step("✓ code style: already clean");
  }

  // ── 3. unit tests
  onStep?.("test: running unit tests…");
  const [tcmd, ...targs] = cmds.test.trim().split(/\s+/);
  const test = await sh([tcmd, ...targs], shadowPath);
  if (test.ok) {
    step("✓ tests: passing");
  } else {
    const files = failingTestFiles(`${test.out}\n${test.err}`);
    step(`⚠ tests: ${files.length || "some"} failing — see copy prompt below`);
    prompts.push({
      title: "fix failing test(s)",
      text: files.length
        ? `Fix failing unit test(s): ${files.join(" ")}. Reproduce/verify with only these (not the full suite): ${cmds.test} ${files.join(" ")}`
        : "Unit tests fail. Find the broken test(s), then fix and verify by running only those (not the full suite).",
    });
  }

  // ── 4. i18n
  onStep?.("i18n: running…");
  const [icmd, ...iargs] = cmds.i18n.trim().split(/\s+/);
  const i18n = await sh([icmd, ...iargs], shadowPath);
  const i18nStatus = (await git(["status", "--porcelain"], shadowPath)).out;
  const changed = i18nStatus
    ? i18nStatus
        .split("\n")
        .filter(Boolean)
        .map((l) => l.slice(3).trim())
    : [];
  if (i18n.ok && changed.length === 0) {
    step("✓ i18n: clean");
  } else {
    step(
      `⚠ i18n: ${i18n.ok ? `${changed.length} file(s) need attention` : "command failed"} — see copy prompt below`,
    );
    const lines = [
      `Running \`${cmds.i18n}\` in this repo did not leave a clean tree. Finish the i18n work.`,
    ];
    if (changed.length) {
      lines.push("Files it changed (likely new/untranslated strings):");
      for (const f of changed.slice(0, 20)) lines.push(`  ${f}`);
      lines.push(
        `Fill in the missing translations (msgstr) for the new/changed entries in those .po/.pot files, then re-run \`${cmds.i18n}\` until the tree is clean.`,
      );
    }
    if (!i18n.ok) {
      lines.push(`\`${cmds.i18n}\` exited with an error:`);
      lines.push(tail(`${i18n.out}\n${i18n.err}`, 12));
    }
    lines.push("Edit only translation files; do not run the test suite.");
    prompts.push({ title: "finish i18n", text: lines.join("\n") });
  }
  // Don't leave the shadow dirty for the next remote-commit check.
  if (changed.length) {
    await git(["checkout", "--", "."], shadowPath);
    await git(["clean", "-fd"], shadowPath);
  }

  return { steps, prompts, error: null };
}
